export const COMPTEUR_INCREMENT_VALEUR = 'COMPTEUR_INCREMENT_VALEUR'
export const COMPTEUR_DECREMENT_VALEUR = 'COMPTEUR_DECREMENT_VALEUR'
export const COMPTEUR_RESET_VALEUR = 'COMPTEUR_RESET_VALEUR'
export const COMPTEUR_SET_VALEUR = 'COMPTEUR_SET_VALEUR'

export const AJOUTER_TASK = 'AJOUTER_TASK'
export const SUPPRIMER_TASK = 'SUPPRIMER_TASK'

export const SET_LOADING = 'SET_LOADING'
export const SET_CITATION = 'SET_CITATION'
export const SET_TABRESULT = 'SET_TABRESULT'
